# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  apt_packages:
    - cmake
    - flex
    - bison
    - libxml2-dev
    - zlib1g-dev

  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

  jobs:
    pre_create_environment:
      - echo "Install igraph into venv and prepare for sphinx build"
      - python -mvirtualenv /home/docs/checkouts/readthedocs.org/user_builds/igraph/envs/latest
      -  /home/docs/checkouts/readthedocs.org/user_builds/igraph/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
      -  /home/docs/checkouts/readthedocs.org/user_builds/igraph/envs/latest/bin/python -m pip install --exists-action=w --no-cache-dir -r doc/source/requirements.txt 
      - /home/docs/checkouts/readthedocs.org/user_builds/igraph/envs/latest/bin/pip wheel -q -w dist .
      - /home/docs/checkouts/readthedocs.org/user_builds/igraph/envs/latest/bin/pip install -q --force-reinstall dist/*.whl
      - /home/docs/checkouts/readthedocs.org/user_builds/igraph/envs/latest/bin/python3 scripts/patch_modularized_graph_methods.py


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/source/requirements.txt

