# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include:
    - vendor/source/igraph
  recursive: true

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  apt_packages:
    - cmake
    - flex
    - bison
    - libxml2-dev
    - zlib1g-dev

  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"

  jobs:
    pre_build:
      - bash ./scripts/rtd_prebuild.sh
      # One website complains about legacy SSL renegotiation (?), skip for now
      #- python -m sphinx -b linkcheck doc/source/ _build/linkcheck


# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: doc/source/requirements.txt

