name: "Build wheels and deploy"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  wheels_manylinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - 3.8
    needs: build_linux
    steps:
    - uses: actions/checkout@v1
    - name: Init C core submodule
      run: git submodule update --init
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run:
        sudo apt-get install gfortran flex bison
    - name: Install dependencies
      run: |
        # Pypi has no pip by default, and ubuntu blocks python -m ensurepip
        # However, Github runners are supposed to have pip installed by default
        # https://docs.github.com/en/actions/guides/building-and-testing-python
        #wget -qO- https://bootstrap.pypa.io/get-pip.py | python
        python -m pip install --upgrade pip
        pip install cibuildwheel
    - name: Wheels (linux)
      env:
        CIBW_BEFORE_BUILD: "yum install -y flex bison libxml2-devel zlib-devel && python setup.py build_c_core"
        CIBW_TEST_COMMAND: "cd {project} && python -m unittest"
        CIBW_SKIP: "cp27-* pp27-* cp35-*"
      run: |
        python setup.py -q sdist
        python -m cibuildwheel --output-dir wheelhouse
    - name: Upload source dist
      uses: actions/upload-artifact@v2
      with:
        name: source-dist
        path: dist/python-igraph-*.tar.gz
    - name: Upload linux wheels
      uses: actions/upload-artifact@v2
      with:
        name: linux-wheels
        path: wheelhouse/*.whl

  wheels_osx:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
        - 3.8
    needs: build_osx
    steps:
    - uses: actions/checkout@v1
    - name: Init C core submodule
      run: git submodule update --init
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheels
    - name: Wheels (OSX)
      if: startsWith(${{ github.ref }}, "refs/tags")
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BEFORE_BUILD: "python setup.py build_c_core"
        CIBW_TEST_COMMAND: "cd {project} && python -m unittest"
    - name: Upload linux wheels
      uses: actions/upload-artifact@v2
      with:
        name: OSX-wheels
        path: wheelhouse/*.whl

  create_release:
    runs-on: ubuntu-latest
    needs:
    - wheels_manylinux
    - wheels_osx
    steps:
    - name: Config deploy
      run: |
        git config --local user.name "ntamas"
        git config --local user.email "ntamas@gmail.com"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Upload binaries and source
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_paths: '["wheelhouse/*.whl", "dist/python-igraph-*.tar.gz"]'

